# Site title and subtitle. This is used in _includes/header.html
title: 'JQuery Emoji'
subtitle: 'a easy way to send smily'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/cokapp/jquery-emoji'

# Default categories (in order) to appear in the navigation
sections: [
    ['demo', '在线演示'],
    ['tut', '如何使用'],
    ['doc', '文档'],
    ['dev', '关于'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/jquery-emoji'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: 'rouge'

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
